name: naturefarm
description: A new Flutter project for NatureFarm ðŸðŸŒ¿
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  url_launcher: ^6.2.5
  intl: ^0.18.0
  webview_flutter: ^4.13.0
  font_awesome_flutter: ^10.5.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/naturefarm_logo.png
    - assets/profile_picture.jpg
